export const GET_RANDOM = 'GET_RANDOM'
export const GET_NAME = 'GET_NAME'
export const GET_RANDOM_QUOTE = 'GET_RANDOM_QUOTE'
export const GET_QUOTE = 'GET_QUOTE'
export const GET_RANDOM_DEAD = 'GET_RANDOM_DEAD'
